package com.example.demo.test;

public enum NomServices {
	TRAVAUXDEPLATRERIEPEINTURE, 
	TRAVAUXDEPLOMBERIE,
	TRAVAUXDEMAÇONNERIE, 
	TRAVAUXDELECTRICITE,
	TRAVAUXDEMENUISERIE, 
	TRAVAUXDINSTALLATION,
	TRAVAUXDEDECORATION;


}
